// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFcNxMLjN5hAaMsueXNB1lkXu3u56EaAw',
    appId: '1:685765304310:web:a5be1a152aa2e33bec31d7',
    messagingSenderId: '685765304310',
    projectId: 'crunch-6d707',
    authDomain: 'crunch-6d707.firebaseapp.com',
    storageBucket: 'crunch-6d707.appspot.com',
    measurementId: 'G-ZQ8CDNHD41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEaJMedIltOXv9qxChXS-yM1ZGXm5SOV4',
    appId: '1:685765304310:android:031790f9b4e7f643ec31d7',
    messagingSenderId: '685765304310',
    projectId: 'crunch-6d707',
    storageBucket: 'crunch-6d707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5fhXAU-bPexp2b2j7xJfhMzLqPX4hOTU',
    appId: '1:685765304310:ios:62fa88e76bfd6391ec31d7',
    messagingSenderId: '685765304310',
    projectId: 'crunch-6d707',
    storageBucket: 'crunch-6d707.appspot.com',
    iosClientId:
        '685765304310-ifmtsn2ln32icjs0ddshq56nml0ib4og.apps.googleusercontent.com',
    iosBundleId: 'com.example.crunch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5fhXAU-bPexp2b2j7xJfhMzLqPX4hOTU',
    appId: '1:685765304310:ios:62fa88e76bfd6391ec31d7',
    messagingSenderId: '685765304310',
    projectId: 'crunch-6d707',
    storageBucket: 'crunch-6d707.appspot.com',
    iosClientId:
        '685765304310-ifmtsn2ln32icjs0ddshq56nml0ib4og.apps.googleusercontent.com',
    iosBundleId: 'com.example.crunch',
  );
}
